# Generated by Django 5.0.7 on 2025-01-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logprocessedrow",
            name="created",
        ),
        migrations.RemoveField(
            model_name="logprocessedrow",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="logprocessedrow",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="logprocessedrow",
            name="updated_by",
        ),
        migrations.AlterField(
            model_name="applicationconfig",
            name="config_type",
            field=models.CharField(
                choices=[
                    ("ACR", "Dictionary ISSN-ACRONYM Path"),
                    ("DAT", "Dictionary PID-DATES Path"),
                    ("ISS", "Dictionary PID-ISSN Path"),
                    ("LAN", "Dictionary PID-FORMAT-LANG Path"),
                    ("PDF", "Dictionary PDF-PID Path"),
                    ("LFF", "Log File Supported Format"),
                ],
                max_length=3,
                verbose_name="Config Type",
            ),
        ),
        migrations.AlterField(
            model_name="collectionconfig",
            name="config_type",
            field=models.CharField(
                choices=[
                    ("LOG", "Logs"),
                    ("MTS", "Metrics"),
                    ("DAY", "Files per Day"),
                    ("EMA", "E-mail"),
                ],
                max_length=3,
                verbose_name="Type",
            ),
        ),
    ]
