# Generated by Django 5.2.12 on 2026-05-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager", "0009_collectionlogfiledatecount_exported_files_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logfiledate",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="logfiledate",
            name="log_file",
        ),
        migrations.RemoveField(
            model_name="logfiledate",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="logfile",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="logfile",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="logfile",
            name="date",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="Date"
            ),
        ),
        migrations.AddField(
            model_name="logfile",
            name="parse_heartbeat_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Parse Heartbeat At"
            ),
        ),
        migrations.DeleteModel(
            name="CollectionLogFileDateCount",
        ),
        migrations.DeleteModel(
            name="LogFileDate",
        ),
    ]
