# Generated by Django 5.0.7 on 2026-03-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collection", "0001_initial"),
        ("source", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last update date",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("preprint", "Preprint"),
                            ("dataset", "Dataset"),
                            ("book", "Book"),
                            ("chapter", "Chapter"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Document Type",
                    ),
                ),
                (
                    "document_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Document ID",
                    ),
                ),
                (
                    "scielo_issn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        null=True,
                        verbose_name="SciELO ISSN",
                    ),
                ),
                (
                    "pid_v2",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=23,
                        null=True,
                        verbose_name="PID V2",
                    ),
                ),
                (
                    "pid_v3",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=23,
                        null=True,
                        verbose_name="PID V3",
                    ),
                ),
                (
                    "pid_generic",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="PID Generic",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Document Title",
                    ),
                ),
                (
                    "identifiers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Identifiers",
                    ),
                ),
                (
                    "files",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Files",
                    ),
                ),
                (
                    "default_lang",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Default Language",
                    ),
                ),
                (
                    "text_langs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Text Languages",
                    ),
                ),
                (
                    "default_media_format",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Default Media Format",
                    ),
                ),
                (
                    "processing_date",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Processing Date",
                    ),
                ),
                (
                    "publication_date",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Publication Date",
                    ),
                ),
                (
                    "publication_year",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=4,
                        null=True,
                        verbose_name="Publication Year",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Extra Data",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "parent_document",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_documents",
                        to="document.document",
                        verbose_name="Parent Document",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        db_index=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="source.source",
                        verbose_name="Source",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "unique_together": {("collection", "document_type", "document_id")},
                "indexes": [
                    models.Index(
                        fields=["collection", "document_type"],
                        name="document_collection_type_idx",
                    ),
                    models.Index(
                        fields=["collection", "scielo_issn"],
                        name="document_collection_issn_idx",
                    ),
                    models.Index(
                        fields=["collection", "pid_v2"],
                        name="document_collection_pidv2_idx",
                    ),
                    models.Index(
                        fields=["collection", "pid_generic"],
                        name="doc_coll_pidgen_idx",
                    ),
                ],
            },
        ),
    ]
