# Generated by Django 5.2.12 on 2026-05-01 22:27

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
        ("log_manager_config", "0003_alter_collectionemail_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogManagerCollectionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "sample_size",
                    models.FloatField(default=0.1, verbose_name="Sample Size"),
                ),
                (
                    "buffer_size",
                    models.IntegerField(default=2048, verbose_name="Buffer Size"),
                ),
                (
                    "expected_logs_per_day",
                    models.IntegerField(
                        default=1, verbose_name="Expected Logs Per Day"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Manager Collection Config",
                "verbose_name_plural": "Log Manager Collection Configs",
            },
        ),
        migrations.RemoveField(
            model_name="collectionlogfilesperday",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionlogfilesperday",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="collectionlogfilesperday",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="collectionurltranslatorclass",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionurltranslatorclass",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="collectionurltranslatorclass",
            name="directory",
        ),
        migrations.RemoveField(
            model_name="collectionurltranslatorclass",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="collectionvalidationparameters",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionvalidationparameters",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="collectionvalidationparameters",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="supportedlogfile",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="supportedlogfile",
            name="updated_by",
        ),
        migrations.RemoveConstraint(
            model_name="collectionemail",
            name="unique_collection_email",
        ),
        migrations.RemoveConstraint(
            model_name="collectionlogdirectory",
            name="unique_collection_path",
        ),
        migrations.RemoveField(
            model_name="collectionemail",
            name="collection",
        ),
        migrations.RemoveField(
            model_name="collectionlogdirectory",
            name="collection",
        ),
        migrations.AddField(
            model_name="collectionemail",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="collectionlogdirectory",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="collectionlogdirectory",
            name="translator_class",
            field=models.CharField(
                default="URLTranslatorClassicSite", verbose_name="URL Translator Class"
            ),
        ),
        migrations.AddField(
            model_name="logmanagercollectionconfig",
            name="collection",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="log_manager_config",
                to="collection.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AddField(
            model_name="logmanagercollectionconfig",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_creator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="logmanagercollectionconfig",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_last_mod_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updater",
            ),
        ),
        migrations.AddField(
            model_name="collectionemail",
            name="config",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to="log_manager_config.logmanagercollectionconfig",
            ),
        ),
        migrations.AddField(
            model_name="collectionlogdirectory",
            name="config",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="directories",
                to="log_manager_config.logmanagercollectionconfig",
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionemail",
            constraint=models.UniqueConstraint(
                fields=("config", "email"), name="unique_config_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="collectionlogdirectory",
            constraint=models.UniqueConstraint(
                fields=("config", "path"), name="unique_config_path"
            ),
        ),
        migrations.DeleteModel(
            name="CollectionLogFilesPerDay",
        ),
        migrations.DeleteModel(
            name="CollectionURLTranslatorClass",
        ),
        migrations.DeleteModel(
            name="CollectionValidationParameters",
        ),
        migrations.DeleteModel(
            name="SupportedLogFile",
        ),
    ]
