# Generated by Django 5.2.12 on 2026-05-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_manager_config", "0004_logmanagercollectionconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionlogdirectory",
            name="translator_class",
            field=models.CharField(
                default="classic", verbose_name="URL Translator Class"
            ),
        ),
    ]
