# Generated by Django 5.0.7 on 2024-11-17 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0002_alter_top100articlesfile_status"),
        ("wagtaildocs", "0013_delete_uploadeddocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleLangByCountryFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUE", "Queued"),
                            ("PAR", "Parsing"),
                            ("PRO", "Processed"),
                            ("ERR", "Error"),
                            ("INV", "Invalidated"),
                        ],
                        default="QUE",
                        max_length=5,
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtaildocs.document",
                        verbose_name="Attachment",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "ArticleLangByCountry File",
                "verbose_name_plural": "ArticleLangByCountry Files",
            },
        ),
        migrations.CreateModel(
            name="ArticleLangByCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation date"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last update date"
                    ),
                ),
                (
                    "collection",
                    models.CharField(max_length=3, verbose_name="Collection"),
                ),
                ("issn", models.CharField(max_length=9, verbose_name="ISSN")),
                ("pid", models.CharField(verbose_name="Publication ID")),
                (
                    "language",
                    models.CharField(max_length=2, verbose_name="Article Language"),
                ),
                (
                    "publication_year",
                    models.PositiveSmallIntegerField(
                        verbose_name="Year of Publication (Site)"
                    ),
                ),
                (
                    "publication_month",
                    models.PositiveSmallIntegerField(
                        verbose_name="Month of Publication (Site)"
                    ),
                ),
                (
                    "access_country",
                    models.CharField(max_length=2, verbose_name="Country of Access"),
                ),
                (
                    "access_year",
                    models.PositiveSmallIntegerField(verbose_name="Year of Access"),
                ),
                (
                    "total_item_requests",
                    models.IntegerField(verbose_name="Total Item Requests"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ArticleLangByCountries",
                "indexes": [
                    models.Index(
                        fields=["collection"], name="metrics_art_collect_aa51c4_idx"
                    ),
                    models.Index(fields=["issn"], name="metrics_art_issn_5fdb8c_idx"),
                    models.Index(fields=["pid"], name="metrics_art_pid_9e802d_idx"),
                    models.Index(
                        fields=["language"], name="metrics_art_languag_e98807_idx"
                    ),
                    models.Index(
                        fields=["access_country"], name="metrics_art_access__f99c3c_idx"
                    ),
                    models.Index(
                        fields=["access_year"], name="metrics_art_access__b836fa_idx"
                    ),
                ],
                "unique_together": {
                    (
                        "collection",
                        "issn",
                        "pid",
                        "language",
                        "publication_year",
                        "publication_month",
                        "access_country",
                        "access_year",
                    )
                },
            },
        ),
    ]
