# Generated by Django 5.0.7 on 2024-11-18 00:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0003_articlelangbycountryfile_articlelangbycountry"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articlelangbycountry",
            unique_together={
                (
                    "collection",
                    "issn",
                    "pid",
                    "language",
                    "publication_year",
                    "publication_month",
                    "access_country",
                )
            },
        ),
    ]
