# Generated by Django 5.0.7 on 2024-11-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0004_alter_articlelangbycountry_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlelangbycountry",
            name="publication_month",
            field=models.CharField(
                max_length=2, verbose_name="Month of Publication (Site)"
            ),
        ),
    ]
