# Generated by Django 5.2.12 on 2026-05-01 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyLogReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_files", models.IntegerField(default=0)),
                ("created_files", models.IntegerField(default=0)),
                ("validated_files", models.IntegerField(default=0)),
                ("invalidated_files", models.IntegerField(default=0)),
                ("errored_files", models.IntegerField(default=0)),
                ("lines_parsed", models.IntegerField(default=0)),
                ("valid_lines", models.IntegerField(default=0)),
                ("discarded_lines", models.IntegerField(default=0)),
                ("ip_local_count", models.IntegerField(default=0)),
                ("ip_remote_count", models.IntegerField(default=0)),
                ("ip_unknown_count", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(verbose_name="Year")),
                ("month", models.IntegerField(verbose_name="Month")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Log Report",
                "verbose_name_plural": "Monthly Log Reports",
                "ordering": ["-year", "-month", "collection__acron3"],
                "unique_together": {("collection", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="WeeklyLogReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_files", models.IntegerField(default=0)),
                ("created_files", models.IntegerField(default=0)),
                ("validated_files", models.IntegerField(default=0)),
                ("invalidated_files", models.IntegerField(default=0)),
                ("errored_files", models.IntegerField(default=0)),
                ("lines_parsed", models.IntegerField(default=0)),
                ("valid_lines", models.IntegerField(default=0)),
                ("discarded_lines", models.IntegerField(default=0)),
                ("ip_local_count", models.IntegerField(default=0)),
                ("ip_remote_count", models.IntegerField(default=0)),
                ("ip_unknown_count", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(verbose_name="Year")),
                ("week", models.IntegerField(verbose_name="ISO Week")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Log Report",
                "verbose_name_plural": "Weekly Log Reports",
                "ordering": ["-year", "-week", "collection__acron3"],
                "unique_together": {("collection", "year", "week")},
            },
        ),
        migrations.CreateModel(
            name="YearlyLogReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_files", models.IntegerField(default=0)),
                ("created_files", models.IntegerField(default=0)),
                ("validated_files", models.IntegerField(default=0)),
                ("invalidated_files", models.IntegerField(default=0)),
                ("errored_files", models.IntegerField(default=0)),
                ("lines_parsed", models.IntegerField(default=0)),
                ("valid_lines", models.IntegerField(default=0)),
                ("discarded_lines", models.IntegerField(default=0)),
                ("ip_local_count", models.IntegerField(default=0)),
                ("ip_remote_count", models.IntegerField(default=0)),
                ("ip_unknown_count", models.IntegerField(default=0)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("year", models.IntegerField(verbose_name="Year")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yearly Log Report",
                "verbose_name_plural": "Yearly Log Reports",
                "ordering": ["-year", "collection__acron3"],
                "unique_together": {("collection", "year")},
            },
        ),
    ]
