# Generated by Django 5.2.12 on 2026-05-01 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="monthlylogreport",
            options={
                "ordering": ["collection__acron3", "year", "month"],
                "verbose_name": "Monthly Log Report",
                "verbose_name_plural": "Monthly Log Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="weeklylogreport",
            options={
                "ordering": ["collection__acron3", "year", "week"],
                "verbose_name": "Weekly Log Report",
                "verbose_name_plural": "Weekly Log Reports",
            },
        ),
        migrations.AlterModelOptions(
            name="yearlylogreport",
            options={
                "ordering": ["collection__acron3", "year"],
                "verbose_name": "Yearly Log Report",
                "verbose_name_plural": "Yearly Log Reports",
            },
        ),
    ]
