# Generated by Django 5.0.7 on 2026-03-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("collection", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Last update date",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("journal", "Journal"),
                            ("book", "Book"),
                            ("preprint_server", "Preprint Server"),
                            ("data_repository", "Data Repository"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="Source Type",
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        verbose_name="Source ID",
                    ),
                ),
                (
                    "scielo_issn",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=9,
                        null=True,
                        verbose_name="SciELO ISSN",
                    ),
                ),
                (
                    "acronym",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        null=True,
                        verbose_name="Source Acronym",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        verbose_name="Source Title",
                    ),
                ),
                (
                    "identifiers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Identifiers",
                    ),
                ),
                (
                    "publisher_name",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Publisher Name",
                    ),
                ),
                (
                    "subject_areas",
                    models.JSONField(
                        default=list,
                        verbose_name="Subject Areas (CAPES)",
                    ),
                ),
                (
                    "wos_subject_areas",
                    models.JSONField(
                        default=list,
                        verbose_name="Subject Areas (WoS)",
                    ),
                ),
                (
                    "default_lang",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Default Language",
                    ),
                ),
                (
                    "publication_date",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        null=True,
                        verbose_name="Publication Date",
                    ),
                ),
                (
                    "publication_year",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=4,
                        null=True,
                        verbose_name="Publication Year",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        null=True,
                        verbose_name="Extra Data",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collection.collection",
                        verbose_name="Collection",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
                "unique_together": {("collection", "source_type", "source_id")},
                "indexes": [
                    models.Index(
                        fields=["collection", "source_type"],
                        name="source_collection_type_idx",
                    ),
                    models.Index(
                        fields=["collection", "scielo_issn"],
                        name="source_collection_issn_idx",
                    ),
                ],
            },
        ),
    ]
