# Generated by Codex on 2026-04-27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("log_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnexpectedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "exception_type",
                    models.TextField(blank=True, null=True, verbose_name="Exception Type"),
                ),
                (
                    "exception_msg",
                    models.TextField(blank=True, null=True, verbose_name="Exception Msg"),
                ),
                ("traceback", models.JSONField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["exception_type"],
                        name="tracker_une_excepti_47ede4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ArticleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update date"),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MUL", "Multiple Articles Returned"),
                            ("ERR", "Data Error"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Data")),
                ("handled", models.BooleanField(default=False, verbose_name="Handled")),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogFileDiscardedLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creation date"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last update date"),
                ),
                (
                    "error_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MET", "Missing Metadata"),
                            ("DOC", "Missing Document"),
                            ("SRC", "Missing Source"),
                            ("URL", "URL Translation"),
                            ("DBE", "Database Error"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Error Type",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Data")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                ("handled", models.BooleanField(default=False, verbose_name="Handled")),
                (
                    "creator",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_creator",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "log_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="log_manager.logfile",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_last_mod_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Updater",
                    ),
                ),
            ],
        ),
    ]
