# Generated by Django 5.2.12 on 2026-05-01 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleevent",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="articleevent",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="UnexpectedEvent",
        ),
        migrations.RemoveField(
            model_name="logfilediscardedline",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="logfilediscardedline",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="logfilediscardedline",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="ArticleEvent",
        ),
    ]
