# Generated by Django 5.0.7 on 2025-01-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mmdb",
            name="hash",
        ),
        migrations.AlterField(
            model_name="mmdb",
            name="file",
            field=models.FileField(upload_to="resources", verbose_name="MMDB File"),
        ),
        migrations.AlterField(
            model_name="mmdb",
            name="id",
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                verbose_name="ID (HASH)",
            ),
        ),
    ]
