# Generated by Django 5.2.12 on 2026-05-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mmdb",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="mmdb",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="robotuseragent",
            name="creator",
        ),
        migrations.RemoveField(
            model_name="robotuseragent",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="robotuseragent",
            name="is_active",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Active"
            ),
        ),
        migrations.AddField(
            model_name="robotuseragent",
            name="source_counter",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="From Atmire/COUNTER"
            ),
        ),
        migrations.AddField(
            model_name="robotuseragent",
            name="source_scielo",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="From SciELO"
            ),
        ),
        migrations.AddField(
            model_name="robotuseragent",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Source URL"
            ),
        ),
        migrations.AlterField(
            model_name="robotuseragent",
            name="last_changed",
            field=models.DateField(blank=True, null=True, verbose_name="Last Changed"),
        ),
    ]
