# Generated by Django 5.0.7 on 2025-01-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0002_remove_mmdb_hash_alter_mmdb_file_alter_mmdb_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mmdb",
            name="file",
        ),
        migrations.AddField(
            model_name="mmdb",
            name="data",
            field=models.BinaryField(default=b"", verbose_name="MMDB Data"),
            preserve_default=False,
        ),
    ]
