# Generated by Django 5.0.7 on 2025-01-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0003_remove_mmdb_file_mmdb_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="mmdb",
            name="url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="URL"
            ),
        ),
    ]
